<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find robomuse_description)/urdf/rack/rack.gazebo.xacro" />

  <xacro:macro name="robomuse_rack" params="name parent *origin">
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
    <link name="${name}_link">
      <inertial>
        <mass value="3.836" />
        <origin xyz="0 0 0.5" />
        <inertia ixx="1641778199.32E-9" ixy="6888946.20E-9" ixz="-25985005.35E-9"
                 iyy="1492340104.52E-9" iyz="-362394063.17E-9" izz="187330520.36E-9" />
      </inertial>

      <visual>
        <origin xyz="0 0 0.3" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://robomuse_description/meshes/rack.stl"  />
        </geometry>

        <material name="Orange" />
      </visual>

      <collision name="${name}_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${base_size_x/4} ${base_size_y/4} ${base_size_z/4}" />
        </geometry>
      </collision>
    </link>

    <!-- extensions -->
    <xacro:rack_gazebo name="${name}" />

  </xacro:macro>
</robot>
